// Package vmrun runs the testbed's Go tests inside a QEMU VM with a stock distribution kernel
// (test level 1b, plan §4.5). One VM boots per test run and executes all test binaries; results
// come back through a read-write share, so the host sees the exit code and the output of every
// package even when the VM dies halfway.
//
// The VM is the isolation: the namespaces, veth pairs and nftables rules the tests create exist
// only in the guest kernel, never on the host.
package vmrun

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Andste82/chaos-gateway/internal/preflight"
	"github.com/Andste82/chaos-gateway/internal/testbed"
)

// Unit is one test binary to run in the guest.
type Unit struct {
	// Name is the file-name-safe name of the package, used for the binary and result files.
	Name string
	// ImportPath is the package under test.
	ImportPath string
	// Dir is the package directory; the guest runs the binary there so testdata is found.
	Dir string
	// Binary is the host path of the compiled test binary (inside the shared work directory).
	Binary string
}

var unsafeName = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

// UnitName turns an import path into a name that is safe as a file name.
func UnitName(importPath string) string {
	n := strings.Trim(unsafeName.ReplaceAllString(importPath, "_"), "_")
	if n == "" {
		return "pkg"
	}
	return n
}

// ShellQuote quotes s for a POSIX shell.
func ShellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// GuestOptions are the settings that end up in the guest script.
type GuestOptions struct {
	// WorkDir is the share the guest may write to; results go to WorkDir/results.
	WorkDir string
	// Emulated says the VM runs without hardware virtualization (testbed.EmulatedEnv).
	Emulated bool
	// Run is an optional -test.run expression; Verbose adds -test.v output.
	Run string
	// TestTimeout is the per-package -test.timeout.
	TestTimeout string
}

// Result files of one unit, inside WorkDir/results.
const (
	exitSuffix = ".exit"
	outSuffix  = ".out"
	doneMarker = "done"
)

// GuestScript returns the shell script that the guest runs. It loads the kernel modules, runs
// every test binary in its package directory and records, per package, the exit code and the
// output. A marker file at the end tells the host that the guest finished.
func GuestScript(o GuestOptions, units []Unit) string {
	var b strings.Builder
	results := filepath.Join(o.WorkDir, "results")
	b.WriteString("#!/bin/sh\n# generated by internal/testbed/vmrun\n")
	b.WriteString("set -u\n")
	if o.Emulated {
		fmt.Fprintf(&b, "export %s=1\n", testbed.EmulatedEnv)
	}
	b.WriteString("export PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n")
	// the same module list as the preflight; a module that cannot load is reported by the
	// preflight inside the tests, not here
	fmt.Fprintf(&b, "modprobe %s 2>/dev/null || true\n", strings.Join(preflight.ModprobeArgs(preflight.Modules()), " "))
	fmt.Fprintf(&b, "mkdir -p %s\n", ShellQuote(results))
	b.WriteString("status=0\n")
	for _, u := range units {
		args := []string{ShellQuote(u.Binary), "-test.v", "-test.count=1"}
		if o.TestTimeout != "" {
			args = append(args, "-test.timeout="+ShellQuote(o.TestTimeout))
		}
		if o.Run != "" {
			args = append(args, "-test.run="+ShellQuote(o.Run))
		}
		out := ShellQuote(filepath.Join(results, u.Name+outSuffix))
		code := ShellQuote(filepath.Join(results, u.Name+exitSuffix))
		fmt.Fprintf(&b, "echo \"=== %s\"\n", u.ImportPath)
		fmt.Fprintf(&b, "( cd %s && %s ) > %s 2>&1\n", ShellQuote(u.Dir), strings.Join(args, " "), out)
		fmt.Fprintf(&b, "rc=$?\necho $rc > %s\ncat %s\n[ $rc -eq 0 ] || status=1\n", code, out)
	}
	fmt.Fprintf(&b, "echo done > %s\nsync\nexit $status\n", ShellQuote(filepath.Join(results, doneMarker)))
	return b.String()
}
