package bird

import (
	"fmt"
	"net/netip"
	"strings"
)

// RemoteLinkLocal is the remote side's own fe80::<its IPv4 address, in hex>/64, derived the same
// way the compiler derives the gateway's (M4c-05), so the hint matches what the gateway side
// actually gets without the two colliding, and never fe80:: itself (see babelLinkLocal).
func RemoteLinkLocal(v4 string) (string, bool) {
	addr, err := netip.ParseAddr(v4)
	if err != nil || !addr.Is4() {
		return "", false
	}
	b := addr.As4()
	ll := netip.AddrFrom16([16]byte{0xfe, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, b[0], b[1], b[2], b[3]})
	return netip.PrefixFrom(ll, 64).String(), true
}

// RenderRemote renders the BIRD configuration for the other end of a link: the gateway's roles
// swapped, the same protocol and timers, and a place to announce the remote side's own prefixes.
// remoteIface is the name of the tunnel interface on the remote machine.
func RenderRemote(c Config, p Protocol, remoteIface string) (string, error) {
	if err := c.Check(); err != nil {
		return "", err
	}
	if !ifaceRE.MatchString(remoteIface) {
		return "", fmt.Errorf("invalid interface %q", remoteIface)
	}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	w("# BIRD configuration of the remote side of the link %s (%s), generated by Chaos Gateway.\n", p.Name, strings.ToUpper(p.Type))
	w("# Add the prefixes of this site to the static protocol below.\n")
	w("router id %s;\n\nprotocol device { scan time 10; }\n\n", p.NeighborAddress)
	w("protocol static announce {\n  ipv4;\n  # route 192.0.2.0/24 unreachable;\n}\n\n")
	switch p.Type {
	case "bgp":
		w("# learned routes go into the operating system's routing table\n")
		w("protocol kernel { ipv4 { import none; export where source ~ [ RTS_BGP ]; }; }\n\n")
		w("protocol bgp gateway {\n  local %s as %d;\n  neighbor %s as %d;\n", p.NeighborAddress, p.BGP.NeighborASN, p.LocalAddress, c.ASN)
		if !p.BGP.Passive {
			w("  passive on;\n")
		}
		w("  hold time %d;\n  keepalive time %d;\n  ipv4 { import all; export where proto = \"announce\"; };\n}\n", p.BGP.HoldTime, p.BGP.KeepaliveTime)
	case "ospf":
		w("protocol kernel { ipv4 { import none; export where source ~ [ RTS_OSPF, RTS_OSPF_IA, RTS_OSPF_EXT1, RTS_OSPF_EXT2 ]; }; }\n\n")
		w("protocol ospf v2 gateway {\n  ipv4 { import all; export where proto = \"announce\"; };\n  area %s {\n    interface %q { type ptp; hello %d; dead %d; };\n  };\n}\n", p.OSPF.Area, remoteIface, p.OSPF.HelloInterval, p.OSPF.DeadInterval)
	case "babel":
		w("protocol kernel { ipv4 { import none; export where source ~ [ RTS_BABEL ]; }; }\n\n")
		// Babel's wire protocol needs an IPv6 link-local address on the tunnel even for IPv4-only
		// routing (M4c-05); the gateway's side gets one from the compiler, the remote side does not
		// manage this file's host and needs the hint instead.
		if ll, ok := RemoteLinkLocal(p.NeighborAddress); ok {
			w("# Babel needs an IPv6 link-local address on the tunnel, e.g.:\n#   ip -6 addr add %s dev %s\n\n", ll, remoteIface)
		}
		w("protocol babel gateway {\n  ipv4 { import all; export where proto = \"announce\"; };\n  interface %q { type tunnel; hello interval %d s; };\n}\n", remoteIface, p.Babel.HelloInterval)
	}
	return b.String(), nil
}
